<?php
return [
	'amazon_ses_access_key' => [
		'group' => 'ses',
		'group_name' => 'Amazon SES Settings',
		'name' => 'amazon_ses_access_key',
		'type' => 'String',
		'quick_form_type' => 'Element',
		'html_type' => 'Text',
		'default' => false,
		'title' => 'Amazon SES acceess key',
		'is_domain' => 1,
		'is_contact' => 0,
		'description' => 'Access key description',
		'help_text' => 'Some help description',
	],
	'amazon_ses_secret_key' => [
		'group' => 'ses',
		'group_name' => 'Amazon SES Settings',
		'name' => 'amazon_ses_secret_key',
		'type' => 'String',
		'quick_form_type' => 'Element',
		'html_type' => 'Text',
		'default' => false,
		'title' => 'Amazon SES secret key',
		'is_domain' => 1,
		'is_contact' => 0,
		'description' => 'Cool descriptio for secret key',
		'help_text' => 'Some help description',
	],
	'amazon_ses_region' => [
		'group' => 'ses',
		'group_name' => 'Amazon SES Settings',
		'name' => 'amazon_ses_region',
		'type' => 'String',
		'quick_form_type' => 'Select',
		'html_type' => 'Select',
		'html_attributes' => [ 'class' => 'crm-select2' ],
		'default' => 'eu-west-1',
		'pseudoconstant' => [ 'callback' => 'CRM_Ses_Ses::get_regions', ],
		'title' => 'Amazon SES Region',
		'is_domain' => 1,
		'is_contact' => 0,
		'description' => 'Cool description for regions',
		'help_text' => 'Some help description',
	],
	'amazon_ses_use_api' => [
		'group' => 'ses',
		'group_name' => 'Amazon SES Settings',
		'name' => 'amazon_ses_use_api',
		'type' => 'Boolean',
		'quick_form_type' => 'YesNo',
		'html_type' => 'radio',
		'default' => false,
		'title' => 'Use Amazon SES API?',
		'is_domain' => 1,
		'is_contact' => 0,
		'description' => 'Use SES API to send emails instead of SMTP',
		'help_text' => 'Some help description',
	]
];